### ISSUE TITLE
ComfyUIIPAdapterPlus appears to be required, not optional

### ISSUE THREAD

**Issue by umiyuki** [Shaamallow/texture-diffusion#14]
According to the README, it appears that ComfyUIIPAdapterPlus needs to be installed on ComfyUI only if IPAdapter is required. But without ComfyUIIPAdapterPlus, even if IPAdapter is not used, the following error occurs on the ComfyUI side. If you install ComfyUIIPAdapterPlus, the error will disappear.
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node IPAdapterUnifiedLoader does not exist.', 'details': “Node ID '# 22'”, ‘extra_info’: {}}

**Comment by Shaamallow** [comment]
Adding that to the readme
